import { useRef, useState } from "react";
import { Play } from "lucide-react";

import { VideoLightbox } from "@/components/video-lightbox";
import { extractVideoId, toAspect, toThumbnailUrl } from "@/lib/youtube";
import type { Video } from "@/types/content";

/** Where a portrait thumbnail has not been generated by YouTube. */
const FALLBACK_THUMBNAIL = "hqdefault.jpg";

/**
 * Thumbnail grid that opens the videos in a lightbox.
 *
 * The tiles are a facade, exactly like YouTubeEmbed: an <img> and a play
 * badge, with no YouTube script and no iframe on the page until someone
 * presses play. That is what makes a page carrying several videos cheap.
 */
export function VideoGallery({ videos, limit }: { videos: Video[]; limit?: number | undefined }) {
  const [active, setActive] = useState<number | null>(null);
  /** The tile that opened the lightbox, so focus can go back to it on close. */
  const triggerRef = useRef<HTMLElement | null>(null);

  const shown = limit === undefined ? videos : videos.slice(0, limit);
  if (shown.length === 0) return null;

  return (
    <>
      <div className="video-grid">
        {shown.map((video, index) => {
          const id = extractVideoId(video.videoUrl);
          const aspect = toAspect(video.videoUrl);

          return (
            <button
              type="button"
              className="video-tile"
              key={`${video.videoUrl}-${index}`}
              onClick={(event) => {
                triggerRef.current = event.currentTarget;
                setActive(index);
              }}
              aria-label={`Play video: ${video.title}`}
            >
              <span className="video-thumb">
                {id && (
                  <img
                    src={toThumbnailUrl(id, aspect)}
                    alt=""
                    loading="lazy"
                    decoding="async"
                    onError={(event) => {
                      const img = event.currentTarget;
                      // One retry against the always-present thumbnail; a
                      // second failure means the image is simply hidden and
                      // the play badge still does the job.
                      if (img.dataset["fallback"]) {
                        img.style.display = "none";
                        return;
                      }
                      img.dataset["fallback"] = "1";
                      img.src = `https://i.ytimg.com/vi/${id}/${FALLBACK_THUMBNAIL}`;
                    }}
                  />
                )}
                <span className="video-play" aria-hidden="true">
                  <Play size={26} fill="currentColor" />
                </span>
              </span>

              <span className="video-tile-copy">
                {video.tag && <span className="video-chip">{video.tag}</span>}
                <strong className="video-tile-title">{video.title}</strong>
                {video.caption && <span className="video-tile-caption">{video.caption}</span>}
              </span>
            </button>
          );
        })}
      </div>

      <VideoLightbox
        videos={shown}
        index={active}
        triggerRef={triggerRef}
        onClose={() => setActive(null)}
        onIndexChange={setActive}
      />
    </>
  );
}
